-- Indexes supporting the Spring Data repository access paths.

CREATE INDEX BKND_TRADE_BOOKED_AT_IX
    ON BKND_TRADE (BOOKED_AT DESC);

CREATE INDEX BKND_TRADE_RESPONSE_AT_IX
    ON BKND_TRADE (RESPONSE_AT);

CREATE INDEX BKND_TRADE_LIMIT_ORDER_IX
    ON BKND_TRADE (LIMIT_ORDER_ID);

CREATE INDEX BKND_LOGIN_EVENT_TIME_IX
    ON BKND_USER_LOGIN_EVENT (LOGGED_AT);

CREATE INDEX BKND_LOGIN_EVENT_USER_IX
    ON BKND_USER_LOGIN_EVENT (USERNAME, LOGGED_AT);

CREATE INDEX BKND_LIMIT_SUBMITTED_AT_IX
    ON BKND_LIMIT_ORDER (SUBMITTED_AT DESC);

CREATE INDEX BKND_LIMIT_STATUS_SUBMIT_IX
    ON BKND_LIMIT_ORDER (STATUS, SUBMITTED_AT DESC);

CREATE INDEX BKND_LIMIT_CB_STATUS_IX
    ON BKND_LIMIT_ORDER (CALLBACK_STATUS, SUBMITTED_AT DESC);

CREATE INDEX BKND_LIMIT_STATUS_CLOSED_IX
    ON BKND_LIMIT_ORDER (STATUS, CLOSED_AT);

CREATE INDEX BKND_LIMIT_RESPONSE_AT_IX
    ON BKND_LIMIT_ORDER (RESPONSE_AT);
