<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example</groupId>
        <artifactId>fx-parent-pom</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>open-api-spec</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator.version}</version>
                <executions>
                    <execution>
                        <id>generate-fx-simulator-contract</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <output>${project.build.directory}/generated-sources/openapi-server</output>
                            <inputSpec>${project.basedir}/src/main/resources/META-INF/resources/openapi/fx-simulator-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-boot</library>
                            <apiPackage>com.example.fx.simulator.api</apiPackage>
                            <modelPackage>com.example.fx.simulator.api.model</modelPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useTags>true</useTags>
                                <useResponseEntity>true</useResponseEntity>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useBeanValidation>true</useBeanValidation>
                                <performBeanValidation>true</performBeanValidation>
                                <openApiNullable>false</openApiNullable>
                                <generateJsonIncludeAnnotations>true</generateJsonIncludeAnnotations>
                                <generateJsonSetterNullsAnnotations>true</generateJsonSetterNullsAnnotations>
                                <optionalNonNullPropertyJsonSetterNulls>FAIL</optionalNonNullPropertyJsonSetterNulls>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>none</documentationProvider>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-fx-simulator-http-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <output>${project.build.directory}/generated-sources/openapi-client</output>
                            <inputSpec>${project.basedir}/src/main/resources/META-INF/resources/openapi/fx-simulator-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-http-interface</library>
                            <apiPackage>com.example.fx.simulator.client</apiPackage>
                            <modelPackage>com.example.fx.simulator.api.model</modelPackage>
                            <generateModels>false</generateModels>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useTags>true</useTags>
                                <useResponseEntity>true</useResponseEntity>
                                <openApiNullable>false</openApiNullable>
                                <generateJsonIncludeAnnotations>false</generateJsonIncludeAnnotations>
                                <generateJsonSetterNullsAnnotations>false</generateJsonSetterNullsAnnotations>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
